### ISSUE TITLE
Consuming documents including barcodes fails

### ISSUE THREAD

**Issue by sturmi** [BenoitAnastay/paperless-home-assistant-addon#108]
Whenever I try to import a document that includes one or some EAN barcode it fails.
Addon log shows:
```
[2024-02-28 07:27:16,191] [INFO] [celery.worker.strategy] Task documents.tasks.consume_file[ff6a4898-a7b2-4eeb-b9bf-61c8dc2f279a] received
 celery@ca5234a0-paperless-ngx:ForkPoolWorker-144]: ./core/src/Result.cpp:140: bool ZXing::Result::operator==(const ZXing::Result&) const: Assertion `lineCount() == 1' failed.
[2024-02-28 07:27:19,066: ERROR/MainProcess] Process 'ForkPoolWorker-144' pid:450501 exited with 'signal 6 (SIGABRT)'
[2024-02-28 07:27:19,126] [ERROR] [celery.worker.request] Task handler raised error: WorkerLostError('Worker exited prematurely: signal 6 (SIGABRT) Job: 143.')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/billiard/pool.py", line 1264, in mark_as_worker_lost
    raise WorkerLostError(
billiard.einfo.ExceptionWithTraceback: 
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/billiard/pool.py", line 1264, in mark_as_worker_lost
    raise WorkerLostError(
billiard.exceptions.WorkerLostError: Worker exited prematurely: signal 6 (SIGABRT) Job: 143.
"""
```

Current version: 1.2.5
Core 2024.2.4
Supervisor 2024.02.0
Operating System 12.0
Frontend 20240207.1
Raspberry Pi 4
4 GB RAM

example:
[European Article Number – Wikipedia.pdf](https://github.com/BenoitAnastay/paperless-home-assistant-addon/files/14429815/European.Article.Number.Wikipedia.pdf)

regards
Thomas

**Comment by sturmi** [comment]
`filename: "{created_year}/{correspondent}/{title}"
language: deu
language_packages: eng deu
default_superuser:
  username: ngxadmin
  email: mail@xyz.de
  password: password
timezone: Europe/Berlin
ssl: false
certfile: fullchain.pem
keyfile: privkey.pem
barcodes_asn: true
barcodes_enabled: false`

**Comment by BenoitAnastay** [comment]
It seem to be related to ZXing library, you can try to use PYZBAR but the recognition is better with ZXing

`PAPERLESS_CONSUMER_BARCODE_SCANNER=PYZBAR`

I'll try to replicate the error and check if its related to last Paperless-NGX updates
