### ISSUE TITLE
Acces denied error #13 when using subdirs in consume folder (/usr/share/hassio/share/paperless/consume)

### ISSUE THREAD

**Issue by wfa001** [BenoitAnastay/paperless-home-assistant-addon#123]
when copying files (pdf) with WinSCP into the consume folder (tree with folders) paperless gives an error 13 access denied for the files in the subfolders. Files in the root folder /usr/share/hassio/share/paperless/consume are 'consumed' without any problems

```
PermissionError: [Errno 13] Permission denied: '/share/paperless/consume/Informationen/2022-07-04 Betriebsanleitung Notstromaggregat.pdf'
[2024-03-16 15:02:53,171] [ERROR] [celery.app.trace] Task documents.tasks.consume_file[1e6e0659-9383-4930-bebf-46140a851511] raised unexpected: ConsumerError("2022-07-04 Betriebsanleitung Notstromaggregat.pdf: The following error occurred while storing document 2022-07-04 Betriebsanleitung Notstromaggregat.pdf after parsing: [Errno 13] Permission denied: '/share/paperless/consume/Informationen/2022-07-04 Betriebsanleitung Notstromaggregat.pdf'")
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/asgiref/sync.py", line 349, in main_wrap
    raise exc_info[1]
  File "/usr/src/paperless/src/documents/consumer.py", line 740, in try_consume_file
    self.original_path.unlink()
  File "/usr/lib/python3.11/pathlib.py", line 1148, in unlink
    os.unlink(self)
```

**Comment by BenoitAnastay** [comment]
It's probably because the files arent created and thus owned by PID:GID 1000:1000 user

**Comment by CR6-SE** [comment]
Same Problem here.

**Comment by BenoitAnastay** [comment]
You better use the paperless user and group ID to create the files and folder for consume directory 

You can change default UID:PID of paperless in the add-on configuration tab, you can even use root (0:0) 
![Screenshot_20240323-225904](https://github.com/BenoitAnastay/paperless-home-assistant-addon/assets/45088785/adff1a7a-119b-4f08-8774-3987022c009f)

**Comment by CR6-SE** [comment]
So I place 1000 for UID and 1000 for GID
or even 0 for UID and 0 for GID (root)

Thx for your Work!
