### ISSUE TITLE
Constant "cannot add item to database" and high CPU Usage

### ISSUE THREAD

**Issue by TheRealSimon42** [BenoitAnastay/paperless-home-assistant-addon#126]
Hello everyone,
I am somehow having a Problem with the Add-on, but am not sure what might be the cause of this issue. 

The logs show the following:

```[2024-03-19 13:47:54,629] [WARNING] [celery.redirected] ^
[2024-03-19 13:47:54,629] [WARNING] [celery.redirected] ^
[2024-03-19 13:47:54,629] [WARNING] [celery.redirected] ^
[2024-03-19 13:47:54,629] [WARNING] [celery.redirected] ^
[2024-03-19 13:47:54,630] [WARNING] [celery.redirected] ^
[2024-03-19 13:47:54,630] [WARNING] [celery.redirected] ^
[2024-03-19 13:47:54,630] [WARNING] [celery.redirected] ^
[2024-03-19 13:47:54,630] [WARNING] [celery.redirected] ^
[2024-03-19 13:47:54,631] [WARNING] [celery.redirected] ^
[2024-03-19 13:47:54,631] [WARNING] [celery.redirected] ^
[2024-03-19 13:47:54,631] [WARNING] [celery.redirected] ^
[2024-03-19 13:47:54,631] [WARNING] [celery.redirected] ^
[2024-03-19 13:47:54,632] [WARNING] [celery.redirected] ^
[2024-03-19 13:47:54,632] [WARNING] [celery.redirected] ^
[2024-03-19 13:47:54,632] [WARNING] [celery.redirected] ^
[2024-03-19 13:47:54,632] [WARNING] [celery.redirected] _dbm
[2024-03-19 13:47:54,632] [WARNING] [celery.redirected] .
[2024-03-19 13:47:54,633] [WARNING] [celery.redirected] error
[2024-03-19 13:47:54,633] [WARNING] [celery.redirected] : 
[2024-03-19 13:47:54,633] [WARNING] [celery.redirected] cannot add item to database
[2024-03-19 13:47:54,695] [WARNING] [celery.redirected] Exception ignored in: 
[2024-03-19 13:47:54,696] [WARNING] [celery.redirected] <function Shelf.__del__ at 0x7fba86258cc0>
[2024-03-19 13:47:54,697] [WARNING] [celery.redirected] Traceback (most recent call last):
[2024-03-19 13:47:54,697] [WARNING] [celery.redirected]   File "/usr/lib/python3.11/shelve.py", line 162, in __del__
[2024-03-19 13:47:54,699] [WARNING] [celery.redirected]     
[2024-03-19 13:47:54,699] [WARNING] [celery.redirected] self.close()
[2024-03-19 13:47:54,700] [WARNING] [celery.redirected]   File "/usr/lib/python3.11/shelve.py", line 144, in close
[2024-03-19 13:47:54,700] [WARNING] [celery.redirected]     
[2024-03-19 13:47:54,701] [WARNING] [celery.redirected] self.sync()
[2024-03-19 13:47:54,701] [WARNING] [celery.redirected]   File "/usr/lib/python3.11/shelve.py", line 168, in sync
[2024-03-19 13:47:54,702] [WARNING] [celery.redirected]     
[2024-03-19 13:47:54,702] [WARNING] [celery.redirected] self[key] = entry
[2024-03-19 13:47:54,703] [WARNING] [celery.redirected]  
[2024-03-19 13:47:54,704] [WARNING] [celery.redirected]  
[2024-03-19 13:47:54,704] [WARNING] [celery.redirected]  
[2024-03-19 13:47:54,704] [WARNING] [celery.redirected]  
[2024-03-19 13:47:54,705] [WARNING] [celery.redirected] ~
[2024-03-19 13:47:54,705] [WARNING] [celery.redirected] ~
[2024-03-19 13:47:54,706] [WARNING] [celery.redirected] ~
[2024-03-19 13:47:54,706] [WARNING] [celery.redirected] ~
[2024-03-19 13:47:54,707] [WARNING] [celery.redirected] ^
[2024-03-19 13:47:54,707] [WARNING] [celery.redirected] ^
[2024-03-19 13:47:54,707] [WARNING] [celery.redirected] ^
[2024-03-19 13:47:54,708] [WARNING] [celery.redirected] ^
[2024-03-19 13:47:54,708] [WARNING] [celery.redirected] ^
[2024-03-19 13:47:54,708] [WARNING] [celery.redirected]   File "/usr/lib/python3.11/shelve.py", line 125, in __setitem__
[2024-03-19 13:47:54,709] [WARNING] [celery.redirected]     
[2024-03-19 13:47:54,709] [WARNING] [celery.redirected] self.dict[key.encode(self.keyencoding)] = f.getvalue()
[2024-03-19 13:47:54,709] [WARNING] [celery.redirected]  
[2024-03-19 13:47:54,710] [WARNING] [celery.redirected]  
[2024-03-19 13:47:54,710] [WARNING] [celery.redirected]  
[2024-03-19 13:47:54,711] [WARNING] [celery.redirected]  
[2024-03-19 13:47:54,711] [WARNING] [celery.redirected] ~
[2024-03-19 13:47:54,711] [WARNING] [celery.redirected] ~
[2024-03-19 13:47:54,712] [WARNING] [celery.redirected] ~
[2024-03-19 13:47:54,712] [WARNING] [celery.redirected] ~
[2024-03-19 13:47:54,712] [WARNING] [celery.redirected] ~
[2024-03-19 13:47:54,713] [WARNING] [celery.redirected] ~
[2024-03-19 13:47:54,713] [WARNING] [celery.redirected] ~
[2024-03-19 13:47:54,713] [WARNING] [celery.redirected] ~
[2024-03-19 13:47:54,713] [WARNING] [celery.redirected] ~
[2024-03-19 13:47:54,714] [WARNING] [celery.redirected] ^
[2024-03-19 13:47:54,714] [WARNING] [celery.redirected] ^
[2024-03-19 13:47:54,714] [WARNING] [celery.redirected] ^
[2024-03-19 13:47:54,714] [WARNING] [celery.redirected] ^
[2024-03-19 13:47:54,715] [WARNING] [celery.redirected] ^
[2024-03-19 13:47:54,715] [WARNING] [celery.redirected] ^
[2024-03-19 13:47:54,715] [WARNING] [celery.redirected] ^
[2024-03-19 13:47:54,716] [WARNING] [celery.redirected] ^
[2024-03-19 13:47:54,716] [WARNING] [celery.redirected] ^
[2024-03-19 13:47:54,716] [WARNING] [celery.redirected] ^
[2024-03-19 13:47:54,716] [WARNING] [celery.redirected] ^
[2024-03-19 13:47:54,717] [WARNING] [celery.redirected] ^
[2024-03-19 13:47:54,717] [WARNING] [celery.redirected] ^
[2024-03-19 13:47:54,717] [WARNING] [celery.redirected] ^
[2024-03-19 13:47:54,717] [WARNING] [celery.redirected] ^
[2024-03-19 13:47:54,718] [WARNING] [celery.redirected] ^
[2024-03-19 13:47:54,718] [WARNING] [celery.redirected] ^
[2024-03-19 13:47:54,718] [WARNING] [celery.redirected] ^
[2024-03-19 13:47:54,719] [WARNING] [celery.redirected] ^
[2024-03-19 13:47:54,719] [WARNING] [celery.redirected] ^
[2024-03-19 13:47:54,719] [WARNING] [celery.redirected] ^
[2024-03-19 13:47:54,719] [WARNING] [celery.redirected] ^
[2024-03-19 13:47:54,720] [WARNING] [celery.redirected] ^
[2024-03-19 13:47:54,720] [WARNING] [celery.redirected] ^
[2024-03-19 13:47:54,720] [WARNING] [celery.redirected] ^
[2024-03-19 13:47:54,721] [WARNING] [celery.redirected] ^
[2024-03-19 13:47:54,721] [WARNING] [celery.redirected] ^
[2024-03-19 13:47:54,721] [WARNING] [celery.redirected] ^
[2024-03-19 13:47:54,721] [WARNING] [celery.redirected] ^
[2024-03-19 13:47:54,722] [WARNING] [celery.redirected] ^
[2024-03-19 13:47:54,722] [WARNING] [celery.redirected] _dbm
[2024-03-19 13:47:54,722] [WARNING] [celery.redirected] .
[2024-03-19 13:47:54,722] [WARNING] [celery.redirected] error
[2024-03-19 13:47:54,722] [WARNING] [celery.redirected] : 
[2024-03-19 13:47:54,723] [WARNING] [celery.redirected] cannot add item to database
2024-03-19 13:47:54,980 WARN exited: celery-beat (exit status 1; not expected)
2024-03-19 13:47:55,983 INFO spawned: 'celery-beat' with pid 3461
celery beat v5.3.6 (emerald-rush) is starting.
2024-03-19 13:47:57,512 INFO success: celery-beat entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
```

(Running on Core i5 NUC)

![Add-on Screenshot](https://github.com/BenoitAnastay/paperless-home-assistant-addon/assets/62359912/3ef2b027-123b-4651-ae89-ee837a0ae840)

Is this some kind of common problem? 😅

**Comment by BenoitAnastay** [comment]
My first guess is that there's something wrong with a file you try to import.

**Comment by TheRealSimon42** [comment]
Consume Directory is empty :(

Do you have any hint on how I can find out, which document is causing trouble?

**Comment by BenoitAnastay** [comment]
Someone had a similar issue https://github.com/paperless-ngx/paperless-ngx/issues/2953 but it wasn't explained.

No one else is reporting this issue with my addon thus you may try to just backup and reinstall the addon completly

**Comment by TheRealSimon42** [comment]
Hm, suspicious.

I even reinstalled the Add-on and started from fresh, error is right there back again (even without a single document) 😅

**Comment by TheRealSimon42** [comment]
HA-Hardware Reboot fixed it. In case someone stumbles upon this:

1. Delete all paperless folders under /share and /addon_configs
2. Reboot Home Assistant Host
3. Reinstall and start fresh. Do NOT reimport your Backup, just add the documents again and do backups more frequently 🙈

**Comment by TheRealSimon42** [comment]
Closing
