### ISSUE TITLE
document_exporter fails with error message 'no such table: documents_correspondent'

### ISSUE THREAD

**Issue by sahnetorti** [BenoitAnastay/paperless-home-assistant-addon#130]
Today I tried to export the full dataset with the built-in command from paperless as a means to have another backup method (I do backup by taring the relevant paperless directories and copy them to another location). I'd prefer the export command as this will make it more flexible in case the database backend changes (i.e. postgres)

Wenn calling the exporter from a ssh session on HAOS with this command:
`docker exec  addon_ca5234a0_paperless-ngx document_exporter ../export`
I get a (long) stack trace, see below.

I also tried directly from within the docker container, issuing the command from the `data` directory with the same result:
`root@ca5234a0-paperless-ngx:/usr/src/paperless/data# document_exporter ../export`

```
paperless docker exec  addon_ca5234a0_paperless-ngx document_exporter ../export
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: no such table: documents_correspondent

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/paperless/src/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.11/dist-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.11/dist-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.11/dist-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.11/dist-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/paperless/src/documents/management/commands/document_exporter.py", line 203, in handle
    self.dump(options["no_progress_bar"])
  File "/usr/src/paperless/src/documents/management/commands/document_exporter.py", line 232, in dump
    serializers.serialize("json", Correspondent.objects.all()),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/core/serializers/__init__.py", line 134, in serialize
    s.serialize(queryset, **options)
  File "/usr/local/lib/python3.11/dist-packages/django/core/serializers/base.py", line 132, in serialize
    for count, obj in enumerate(queryset, start=1):
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/db/models/query.py", line 398, in __iter__
    self._fetch_all()
  File "/usr/local/lib/python3.11/dist-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.11/dist-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/usr/local/lib/python3.11/dist-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.11/dist-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/db/backends/sqlite3/base.py", line 328, in execute
    return super().execute(query, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
django.db.utils.OperationalError: no such table: documents_correspondent
```

Any help appreciated :)

**Comment by BenoitAnastay** [comment]
I'll have a look, I know that some CLI tools weren't updated when they made a GUI

**Comment by sahnetorti** [comment]
From the current documentation the exporter should still be working, so I do not think this is the issue at hand.

I poked around a bit more. It seems when I am inside the docker container (docker exec -it container_name sh) all the volume mounts are not available from within the session. After a failed exporter command an empty sqlite file shows up in '/usr/src/paperless/data'.
This pretty much looks like the 'docker exec' does not see the mounted volumes at all, which strikes me quite odd. Also other cli commands fail with similar messages (just mentioning different tables that are not found).

I am not a docker expert but would expect that volume mounts are available when doing 'docker exec'.

**Comment by BenoitAnastay** [comment]
I do use this command regularly to edit files without rebuilding the whole container and it works well, except I use bash instead

**Comment by BenoitAnastay** [comment]
I do think that the root cause of your issue is that the environement variables aren't loaded

**Comment by sahnetorti** [comment]
Great, that worked! :)
Thanks a lot!

**Comment by mansellrace** [comment]
Hi, I am not an expert on docker and home assistant addons.
I am also trying to use document_importer but I have the same problem of not being able to see the folders.
I can't figure out how and where to add the variables of enviroment
Can you give me a quick tip?

**Comment by BenoitAnastay** [comment]
@mansellrace type it just before your command prompt like in my example above
