### ISSUE TITLE
PermissionError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by BernhardMaier** [BenoitAnastay/paperless-home-assistant-addon#189]
I recently installed the Add-On (v2.1.5) in Home Assistant (v2024.10.4 running in HA OS on a RasPi4), configured it, created a shared storage on my NAS, added this storage in HA and started the Add-On. It starts and has access to the storage (i see some newly created folders there), but it seems that the initial migration can't complete successfully because of permission issues.

The main error is the following:
`PermissionError: [Errno 13] Permission denied: '/share/paperless/media/media.lock'`

The complete log looks like this:
```
  Applying documents.1055_alter_storagepath_path...Paperless-ngx docker container starting...
Installing languages...
Package tesseract-ocr-deu already installed!
Package tesseract-ocr-eng already installed!
Creating directory scratch directory /tmp/paperless
Adjusting permissions of paperless files. This may take a while.
changed ownership of '/share/paperless/media' from root:root to paperless:paperless
changed ownership of '/share/paperless/media/documents' from root:root to paperless:paperless
changed ownership of '/share/paperless/media/documents/originals' from root:root to paperless:paperless
changed ownership of '/share/paperless/media/documents/thumbnails' from root:root to paperless:paperless
changed ownership of '/share/paperless/consume' from root:root to paperless:paperless
Waiting for Redis...
Connected to Redis broker.
Apply database migrations...
Operations to perform:
  Apply all migrations: account, admin, auditlog, auth, authtoken, contenttypes, django_celery_results, documents, guardian, paperless, paperless_mail, sessions, socialaccount
Running migrations:
Traceback (most recent call last):
  File "/usr/src/paperless/src/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.11/dist-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.11/dist-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.11/dist-packages/django/core/management/base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.11/dist-packages/django/core/management/base.py", line 459, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/core/management/base.py", line 107, in wrapper
    res = handle_func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/core/management/commands/migrate.py", line 357, in handle
    post_migrate_state = executor.migrate(
                         ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/db/migrations/executor.py", line 135, in migrate
    state = self._migrate_all_forwards(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
    state = self.apply_migration(
            ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/db/migrations/executor.py", line 255, in apply_migration
    state = migration.apply(state, schema_editor)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/django/db/migrations/migration.py", line 132, in apply
    operation.database_forwards(
  File "/usr/local/lib/python3.11/dist-packages/django/db/migrations/operations/special.py", line 196, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/usr/src/paperless/src/documents/migrations/1055_alter_storagepath_path.py", line 15, in convert_from_format_to_template
    with transaction.atomic(), FileLock(settings.MEDIA_LOCK):
  File "/usr/local/lib/python3.11/dist-packages/filelock/_api.py", line 376, in __enter__
    self.acquire()
  File "/usr/local/lib/python3.11/dist-packages/filelock/_api.py", line 332, in acquire
    self._acquire()
  File "/usr/local/lib/python3.11/dist-packages/filelock/_unix.py", line 42, in _acquire
    fd = os.open(self.lock_file, open_flags, self._context.mode)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/share/paperless/media/media.lock'
```

Is this a known issue? If yes, how can i fix it? If not, how can i provide help to identify and solve it?

**Comment by BenoitAnastay** [comment]
You can change the UID and GID of paperless to match the owner of the host folder

**Comment by BernhardMaier** [comment]
Thanks for the advice. With a little help of ChatGPT i adjusted the IDs in the Config, but this not solved the problem, the same exception still occures. I use CIFS/SMB for the connection with the NAS, so i will try to change it to use NFS, maybe this can help.

**Comment by BernhardMaier** [comment]
Ok, got it to work and yes, using NFS instead of CIFS/SMB solved it.

**Comment by BenoitAnastay** [comment]
@nikl0n There is couple things to test.

If you can enable ACL on your CIFS server, change running UID:GID of paperless, run a chmod, chown ...

It's hard to tell you how to troubleshot since every system is different

**Comment by nikl0n** [comment]
I'll briefly explain my setup and how things currently stand with me.

I have two network storages (NTFS and ext3) connected to my Fritz.box via USB. I can access these via CIFS in my local network. 

I have bought a Home Assistant Green. There I have integrated my network storage with the name "paperless" using the storage share.

I have installed your add-on paperless-ngx on the Home Assistant. The folders "consume" and "media" were created but when creating the "media.lock" I get the following error message: 
`PermissionError: [Errno 13] Permission denied: '/share/paperless/media/media.lock'.`

My folder on the Home Assistant /share/paperless that came through the network share has the following mount:
`mount | grep paperless`
`/myLocalIp/fritz.nas/volume/home-assistant-paperless on /share/paperless type cifs (rw,relatime,vers=3.0,cache=none,username=FritzUsername,uid=1000,forceuid,gid=1000,forcegid,addr=192.168.178.1,file_mode=0755,dir_mode=0755,iocharset=utf8,soft,nounix,mapposix,noperm,reparse=nfs,rsize=65536,wsize=65536,bsize=1048576,retrans=1,echo_interval=60,actimeo=1,closetimeo=1)`

This folder "paperless" has the following properties:
```
➜  /share ls -la
total 8
drwxr-xr-x    3 root     root          4096 Mar 23 22:04 .
drwxr-xr-x    1 root     root          4096 Mar 22 21:27 ..
drwxr-xr-x    2 1000     1000             0 Mar 24 14:12 paperless
```

In my Docker container of paperless, the user "paperless" who creates the files and folders has the id "1000".

I don't know how to activate ACL on my Fritz.box.

I have also tried to give the folder "paperless" the 777 authorization with chmod, but unfortunately this does not work.
```
➜  /share ls -l 
total 0
drwxr-xr-x    2 1000     1000             0 Mar 24 14:12 paperless
➜  /share chmod -R 777 paperless
➜  /share ls -l 
total 0
drwxr-xr-x    2 1000     1000             0 Mar 24 14:12 paperless
```

I hope you were able to follow the introduction to my setup and what I have done so far.

Do you have any idea what I need to do?

**Comment by BenoitAnastay** [comment]
Everything seems right on Home Assistant side, I see a lot of similar issue with Fritz!Box but since I don't have one I can't really help.

I can suggest you to look over internet for your issue, also you can check if login from elsewhere is working as expected (read and write permissions)

**Comment by nikl0n** [comment]
I have a friend who runs a synology as NAS and not a fritz.box like me. Unfortunately, he has the same problem as me.

I tried a little and found out the following:
```
➜  /share mount | grep paperless    
//myLocalIp/fritz.nas/USB-SanDisk3-2Gen1-01/home-assistant-paperless on /share/paperless type cifs (rw,relatime,vers=3.1.1,cache=strict,username=fritzUsername,uid=1000,forceuid,gid=1000,forcegid,addr=myLocalIp,file_mode=0777,dir_mode=0777,soft,nounix,serverino,mapposix,reparse=nfs,rsize=65536,wsize=65536,bsize=1048576,retrans=1,echo_interval=60,actimeo=1,closetimeo=1)
➜  /share la
total 0      
drwxrwxrwx    2 1000     1000           0 Mar 25 10:29 paperless
➜  /share docker ps | grep paperless
5deb2d3aacb1   ghcr.io/benoitanastay/paperless-ngx/aarch64:2.3.0           "/init"               18 seconds ago   Up 17 seconds                                                       addon_ca5234a0_paperless-ngx
➜  /share docker exec -it 5deb2 /bin/bash

root@ca5234a0-paperless-ngx:/usr/src/paperless/src# mount | grep /share/paperless
//myLocalIp/fritz.nas/USB-SanDisk3-2Gen1-01/home-assistant-paperless on /share/paperless type cifs (rw,relatime,vers=3.1.1,cache=strict,username=fritzUsername,uid=0,noforceuid,gid=0,noforcegid,addr=myLocalIp,file_mode=0755,dir_mode=0755,soft,nounix,mapposix,reparse=nfs,rsize=65536,wsize=65536,bsize=1048576,retrans=1,echo_interval=60,actimeo=1,closetimeo=1)
root@ca5234a0-paperless-ngx:/usr/src/paperless/src# cd /share
root@ca5234a0-paperless-ngx:/share# ls -la
total 8
drwxr-xr-x 3 root root 4096 Mar 25 11:36 .
drwxr-xr-x 1 root root 4096 Mar 25 11:36 ..
drwxr-xr-x 2 root root    0 Mar 25 10:29 paperless
root@ca5234a0-paperless-ngx:/share#
```

The mount on the host system works perfectly. As you can see, the permissions are now on the user 1000:1000 (which is the paperless user in the Docker container)

However, if you are in the Docker container itself and look at the permissions and the mount, you can see that they are still incorrect (uid=0, gid=0, etc.). Even if you try to change them with chmod, chwon, etc., it does not work because you are not the creator of the folder. Then I also tried to change the mount in the Docker container, but unfortunately that doesn't work either, because you need superuser rights for that.

```
root@ca5234a0-paperless-ngx:/share# umount /share/paperless
umount: /share/paperless: must be superuser to unmount.
```

Can you perhaps help me with this?

**Comment by BenoitAnastay** [comment]
If you change UID and GID of paperless to 0:0 does it fix it?

**Comment by nikl0n** [comment]
That was the solution, thank you!

**Comment by bpanucci** [comment]
Hi, thanks for the solution. Can you please describe, how to change UID and GID of paperless. I did it with `usermod -u 0 -g 0 -o paperless`. After restarting the add-on, the issue occurred again.

**Comment by nikl0n** [comment]
![Image](https://github.com/user-attachments/assets/cbcf6138-16c3-48f6-a949-381caccf54dc)

**Comment by bpanucci** [comment]
Thanks for the help. Sometimes the solution is too obvious.
