### ISSUE TITLE
Feature / How-To: How to trigger the Management utils? 

### ISSUE THREAD

**Issue by dreamworks** [BenoitAnastay/paperless-home-assistant-addon#196]
How would I trigger the Management utils them:
https://docs.paperless-ngx.com/administration/#management-commands

Is it be possible to use buttons within HA to trigger those?

**Comment by BenoitAnastay** [comment]
You can use the shell command feature of home assistant 

https://www.home-assistant.io/integrations/shell_command/

**Comment by dreamworks** [comment]
Morning & thx a lot..

>docker exec -it addon_ca5234a0_paperless-ngx document_retagger -s

gives the following error. Any hints?

Traceback (most recent call last):^M
  File "/usr/local/lib/python3.11/dist-packages/django/db/backends/utils.py", line 105, in _execute^M
    return self.cursor.execute(sql, params)^M
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^M
  File "/usr/local/lib/python3.11/dist-packages/django/db/backends/sqlite3/base.py", line 354, in execute^M
    return super().execute(query, params)^M
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^M
sqlite3.OperationalError: no such table: documents_document^M
^M
The above exception was the direct cause of the following exception:^M
^M
Traceback (most recent call last):^M
  File "/usr/src/paperless/src/manage.py", line 10, in <module>^M
    execute_from_command_line(sys.argv)^M
  File "/usr/local/lib/python3.11/dist-packages/django/core/management/__init__.py", line 442, in execute_from_command_line^M
    utility.execute()^M
  File "/usr/local/lib/python3.11/dist-packages/django/core/management/__init__.py", line 436, in execute^M
    self.fetch_command(subcommand).run_from_argv(self.argv)^M

**Comment by BenoitAnastay** [comment]
You will need to add envirenement variables into your command.

```
PAPERLESS_DATA_DIR=/config/data PAPERLESS_MEDIA_ROOT=/share/paperless/media document_rettager-s
```

**Comment by paviro** [comment]
Could you elaborate a bit more on this? Aren't the shell commands executed in the home assistant container? How can this execute things in the paperless container / how would I tell home assistant that it should?

**Comment by BenoitAnastay** [comment]
Using `docker exec -it` using the addon slug, it depends if you use stable or edge repository.

The command will be run inside the addon, thus cannot access host folder outsides the shared ones 

exemple 
```
docker exec -it addon_ca5234a0_paperless-ngx bash
```

**Comment by paviro** [comment]
I just get 

```
Error running command: `docker exec --user paperless -it addon_55eca821_paperless-ngx document_exporter --data-only --no-progress-bar /share/paperless/backup`, return code: 127

```

When I do this. Executing `docker exec --user paperless -it addon_55eca821_paperless-ngx document_exporter --data-only --no-progress-bar /share/paperless/backup` works when doing it with the advanced ssh plugin but not the normal web terminal one as docker is not available in that context is it really inside of shell commands?

**Comment by BenoitAnastay** [comment]
I don't know why there is a user argument in your command line.

Could you explain why you have added this?

**Comment by paviro** [comment]
I added it so the document_exporter runs as the paperless user instead of root as paperless seems to run under that user? Maybe not necessary but seems to work fine this way when running it in https://github.com/hassio-addons/addon-ssh

**Comment by BenoitAnastay** [comment]
My bad, try this solution 

https://community.home-assistant.io/t/run-docker-exec-from-shell-command-integration-or-other-tricks/400810/7?u=benoitanastay

**Comment by paviro** [comment]
Thanks not really super keen to add ssh keys into the home assistant install as this seems like a very "unsupported hack". Will try for now but I think a way that doesn't require this would be welcome!

**Comment by BenoitAnastay** [comment]
Indeed, it's the official workaround since add-on stdin seems depreciated (I should check if that's the case)
